# Generated by Django 4.1.7 on 2023-02-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('crm', models.CharField(max_length=10, verbose_name='CRM')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'unique_together': {('nome', 'crm')},
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'unique_together': {('horario',)},
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Data alocação')),
                ('horarios', models.ManyToManyField(to='agenda.horario')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'unique_together': {('medico', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('data_agendamento', models.DateField(auto_now_add=True, verbose_name='Data do agendamento')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.agenda')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'unique_together': {('agenda', 'horario')},
            },
        ),
    ]
