# Generated by Django 4.1.7 on 2023-02-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['horario'], 'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
    ]
